#pragma config(Sensor, S1,     color,          sensorColorNxtFULL)

#pragma config(Motor,  motorA,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          clock,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          sorter,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard  !!*//

#define startsorting 1
#define sorted 2


task main()
{
start:
	if(message == 1)
		goto start;
	setMotorTarget(arm,140,30);
	waitUntilMotorStop(arm);
	delay(3000);

sortIt:
	switch(SensorValue[color]){
	case YELLOWCOLOR:
		setMotorTarget(clock, 90, 20);
		waitUntilMotorStop(clock);
		delay(1000);
		break;
	case REDCOLOR:
		setMotorTarget(sorter, 90, 50);
		waitUntilMotorStop(sorter);
		delay(100);
		setMotorTarget(clock,90,20);
		waitUntilMotorStop(clock);
		delay(1000);
		setMotorTarget(sorter, -90, -40);
		waitUntilMotorStop(sorter);
		break;
	case BLUECOLOR:
		setMotorTarget(sorter, 180, 50);
		waitUntilMotorStop(sorter);
		delay(100);
		setMotorTarget(clock,90,20);
		waitUntilMotorStop(clock);
		delay(1000);
		setMotorTarget(sorter, 180, -40);
		waitUntilMotorStop(sorter);
		break;
	case GREENCOLOR:
		setMotorTarget(sorter, -90, -50);
		waitUntilMotorStop(sorter);
		delay(100);
		setMotorTarget(clock,90,20);
		waitUntilMotorStop(clock);
		delay(1000);
		setMotorTarget(sorter, 90, 40);
		waitUntilMotorStop(sorter);
		break;
		case BLACKCOLOR:
		goto end;
		default:

	}
goto sortIt;
end:
	setMotorTarget(arm,-140,-20);
	waitUntilMotorStop(arm);
	sendMessage(sorted);
}
