#pragma config(Sensor, S1,     color,          sensorColorNxtFULL)

#pragma config(Motor,  motorA,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          clock,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          sorter,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard  !!*//

#define startsorting 1
#define sorted 2


int total, red, blu, grn, ylw = 0;


void display(){
	nxtDisplayString(0, "TOTAL BALLS SORTED: %d", total); 	
	nxtDisplayString(1,"RED: %d", red); 
	nxtDisplayString(2,"BLUE: %d", blu); 
	nxtDisplayString(3, "YELLOW: %d", ylw); 
	nxtDisplayString(4, "GREEN: %d", grn); 
}

void counter(){
	total++;
	display();
}

task main()
{
start:
	if(message == 1)
		goto start;
	setMotorTarget(arm,140,30);
	waitUntilMotorStop(arm);
	delay(3000);

sortIt:
	switch(SensorValue[color]){
	case YELLOWCOLOR:
		ylw++;
		counter();
		setMotorTarget(clock, 90, 20);
		waitUntilMotorStop(clock);
		delay(1000);
		break;
	case REDCOLOR:
		red++;
		counter();
		setMotorTarget(sorter, 90, 50);
		waitUntilMotorStop(sorter);
		delay(100);
		setMotorTarget(clock,90,20);
		waitUntilMotorStop(clock);
		delay(1000);
		setMotorTarget(sorter, -90, -40);
		waitUntilMotorStop(sorter);
		break;
	case BLUECOLOR:
		blu++;
		counter();
		setMotorTarget(sorter, 180, 50);
		waitUntilMotorStop(sorter);
		delay(100);
		setMotorTarget(clock,90,20);
		waitUntilMotorStop(clock);
		delay(1000);
		setMotorTarget(sorter, 180, -40);
		waitUntilMotorStop(sorter);
		break;
	case GREENCOLOR:
		grn++;
		counter();
		setMotorTarget(sorter, -90, -50);
		waitUntilMotorStop(sorter);
		delay(100);
		setMotorTarget(clock,90,20);
		waitUntilMotorStop(clock);
		delay(1000);
		setMotorTarget(sorter, 90, 40);
		waitUntilMotorStop(sorter);
		break;
		case BLACKCOLOR:
		goto end;
		default:

	}
goto sortIt;
end:
	setMotorTarget(arm,-140,-20);
	waitUntilMotorStop(arm);
	sendMessage(sorted);
}
